
networks:
  craftista-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    image: craftista-frontend:${FRONTEND_VERSION:-v1}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PRODUCTS_API_BASE_URI=http://catalogue:5000
      - RECOMMENDATION_BASE_URI=http://recco:8080
      - VOTING_BASE_URI=http://voting:8080
    depends_on:
      - catalogue
      - recco
      - voting
    networks:
      - craftista-network

  catalogue:
    build: ./catalogue
    image: craftista-catalogue:${CATALOGUE_VERSION:-v1}
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://catalogue-db:27017/craftista
    depends_on:
      - catalogue-db
    networks:
      - craftista-network

  catalogue-db:
    image: mongo:${MONGO_VERSION:-latest}
    ports:
      - "27017"
    volumes:
      - catalogue-db-data:/data/db
    networks:
      - craftista-network
    restart: unless-stopped

  voting:
    build: ./voting
    image: craftista-voting:${VOTING_VERSION:-v1}
    ports:
      - "8080:8080"
    networks:
      - craftista-network


  recco:
    build: ./recommendation
    image: craftista-recco:${RECCO_VERSION:-v1}
    ports:
      - "8081:8080"
    networks:
      - craftista-network

volumes:
  catalogue-db-data: