apiVersion: apps/v1
kind: Deployment
metadata:
  name: recco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recco
  template:
    metadata:
      labels:
        app: recco
    spec:
      containers:
      - name: recco
        image: 8060633493/craftista-recommendation:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "128m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: recco
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recco