[tool.bandit]
exclude_dirs = ["tests", "venv", ".git", "__pycache__"]
skips = ["B101", "B104"]  # Add any tests you want to skip
targets = ["."]  # Directories to scan

[tool.bandit.assert_used]
skips = ["*_test.py", "test_*.py"]