apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: craftista-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 8060633493/craftista-catalogue:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: craftista-production
spec:
  selector:
    app: catalogue
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP