apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: craftista-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 8060633493/craftista-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PRODUCTS_API_BASE_URI
          value: "http://catalogue:5000"
        - name: RECOMMENDATION_BASE_URI
          value: "http://recco:8080"
        - name: VOTING_BASE_URI
          value: "http://voting:8080"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: craftista-production
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP