apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: craftista-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation
        image: 8060633493/craftista-recco:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: recco
  namespace: craftista-production
spec:
  selector:
    app: recommendation
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP